# Hypothesis Testing & EDA

## Objectives

- Carry out hypothesis testing using statistical analysis techniques.
- Carry out Qualitative Analysis.
- Carry out Predicitve Analysis using Linear Regression.

## Inputs

- data/outputs/clinical_trials_no_missing_values.csv

## Outputs

- INSERT UPDATED DATASET

_________

The clinical trials dataset with no missing values will be loaded into this notebook.

The necessary libraries to conduct the analysis will be imported into this notebook.

In [149]:
# Import necessary libraries for data analysis and visualization (assistance from CoPilot)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns  
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.manifold import TSNE
from sklearn.cluster import DBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer
import os

## Hypothesis Testing

Import the dataset as a CSV file to perform the analysis.

In [150]:
# Load the cleaned dataset 
df = pd.read_csv('../data/outputs/clinical_trials_no_missing_values.csv')
df.head()

,Unnamed: 0,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition,Start_Month_Name,Start_Year_Period,Enrolled_Participants
0,0,GSK,"An Open-Label, Non-Randomized Pharmacokinetic ...",The main purpose of this study is to compare h...,2006,9,Phase 1,29,Completed,"Purpura, Thrombocytopenic, Idiopathic",September,2006-2010,<50
1,1,Sanofi,"A Randomized, Double-blind, Placebo-controlled...",Primary Objective: To evaluate the efficacy of...,2018,11,Phase 3,360,Recruiting,Giant Cell Arteritis,November,2016-2020,100-499
2,2,Pfizer,A Multi Center Randomized Cross Over Double Bl...,This is a pilot study to generate hypotheses a...,2007,3,Phase 2,27,Completed,Prostatic Hyperplasia,March,2006-2010,<50
3,3,Novartis,"A Double-blind, Randomized, Placebo-controlled...",This study will evaluate the effect of FTY720 ...,2008,9,Phase 2,36,Completed,Asthma,September,2006-2010,<50
4,4,Novartis,"A Two Part Study Including a Randomized, Doubl...",This study is designed to enable optimal dose ...,2013,8,Phase 1,93,Terminated,Hypertension,August,2011-2015,50-99

Remove duplicated index from loaded dataset.

In [151]:
# Check if 'Unnamed: 0' exists in the DataFrame and drop it
if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)   
df.head()

,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition,Start_Month_Name,Start_Year_Period,Enrolled_Participants
0,GSK,"An Open-Label, Non-Randomized Pharmacokinetic ...",The main purpose of this study is to compare h...,2006,9,Phase 1,29,Completed,"Purpura, Thrombocytopenic, Idiopathic",September,2006-2010,<50
1,Sanofi,"A Randomized, Double-blind, Placebo-controlled...",Primary Objective: To evaluate the efficacy of...,2018,11,Phase 3,360,Recruiting,Giant Cell Arteritis,November,2016-2020,100-499
2,Pfizer,A Multi Center Randomized Cross Over Double Bl...,This is a pilot study to generate hypotheses a...,2007,3,Phase 2,27,Completed,Prostatic Hyperplasia,March,2006-2010,<50
3,Novartis,"A Double-blind, Randomized, Placebo-controlled...",This study will evaluate the effect of FTY720 ...,2008,9,Phase 2,36,Completed,Asthma,September,2006-2010,<50
4,Novartis,"A Two Part Study Including a Randomized, Doubl...",This study is designed to enable optimal dose ...,2013,8,Phase 1,93,Terminated,Hypertension,August,2011-2015,50-99

In [152]:
# Check pandas DataFrame shape
df.shape

(9439, 12)

## Clustering

Cluster the condition column in dataset to increase accuracy of testing and enhance visualisations. Earlier investiagtion of the dataset revealled multiple similiar/same conditions have been inputted as unique entries.

Identify the top 30 recurring conditions present in the Condition column, to increase variation and reduce bias in cluster. Identification of the top 30 recurring conditions allows for a more accurate represenation of the data.

In [153]:
# Count the occurrences of each condition
top_conditions = df['Condition'].value_counts().head(20)

# Display the top 20 recurring conditions
print("Top 20 Recurring Conditions:")
print(top_conditions)

Top 20 Recurring Conditions:
Condition
Diabetes Mellitus, Type 2                 373
Breast Neoplasms                          264
Pulmonary Disease, Chronic Obstructive    241
Arthritis, Rheumatoid                     240
Hypertension                              231
Influenza, Human                          227
Asthma                                    215
Schizophrenia                             199
Diabetes Mellitus                         189
Lung Neoplasms                            160
Alzheimer Disease                         142
Hepatitis                                 134
Psoriasis                                 131
Hypercholesterolemia                      119
HIV Infections                            109
Prostatic Neoplasms                       105
Infection                                  98
Colorectal Neoplasms                       94
Hepatitis B                                94
Anemia                                     90
Name: count, dtype: int64

All 20 conditions identified will be used to improve condition mapping during clustering.

Check distance matrix has no negative values, so clustering can be conducted.

In [154]:
print("Minimum value in distance matrix:", distance_matrix.min())
print("Maximum value in distance matrix:", distance_matrix.max())

Minimum value in distance matrix: 0.0
Maximum value in distance matrix: 1.0

In [155]:
distance_matrix = np.clip(distance_matrix, 0, None)  # Clip negative values to 0

Check cosine similarity matrix has no negative values, so clustering can be conducted.

In [156]:
print("Minimum value in cosine similarity matrix:", cosine_sim.min())
print("Maximum value in cosine similarity matrix:", cosine_sim.max())

Minimum value in cosine similarity matrix: 0.0
Maximum value in cosine similarity matrix: 1.0000000000000004

Apply DBSCAN clustering to group condtions into clusters.

In [157]:
clustering_model = DBSCAN(eps=1.4, min_samples=2, metric='precomputed')

In [158]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import DBSCAN
import numpy as np

# Preprocess the Condition column
df['Condition_cleaned'] = df['Condition'].str.lower().str.replace(r'[^a-z\s]', '', regex=True).str.strip()

# Vectorize the Condition column using TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['Condition_cleaned'])

# Compute cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix)

# Debug: Check cosine similarity range
print("Minimum value in cosine similarity matrix:", cosine_sim.min())
print("Maximum value in cosine similarity matrix:", cosine_sim.max())

# Convert cosine similarity to a distance matrix and ensure non-negative values
distance_matrix = 1 - cosine_sim
distance_matrix = np.clip(distance_matrix, 0, None)  # Clip negative values to 0

# Debug: Check distance matrix range
print("Minimum value in distance matrix:", distance_matrix.min())
print("Maximum value in distance matrix:", distance_matrix.max())

# Apply DBSCAN clustering
clustering_model = DBSCAN(eps=1.4, min_samples=2, metric='precomputed')
clusters = clustering_model.fit_predict(distance_matrix)  # Use the corrected distance matrix

# Add cluster labels to the DataFrame
df['Condition_cluster'] = clusters

# Display the clustered conditions
clustered_conditions = df[['Condition', 'Condition_cluster']].sort_values(by='Condition_cluster')
print(clustered_conditions)

Minimum value in cosine similarity matrix: 0.0
Maximum value in cosine similarity matrix: 1.0000000000000004
Minimum value in distance matrix: 0.0
Maximum value in distance matrix: 1.0
                                       Condition  Condition_cluster
0          Purpura, Thrombocytopenic, Idiopathic                  0
6288                              Lung Neoplasms                  0
6289                         Depressive Disorder                  0
6290                                      Asthma                  0
6291  Sleep Initiation and Maintenance Disorders                  0
...                                          ...                ...
3147                   Diabetes Mellitus, Type 2                  0
3148                          Dermatitis, Atopic                  0
3149              Carcinoma, Non-Small-Cell Lung                  0
3133                    Urinary Tract Infections                  0
9438                              Osteoarthritis                  0

[9439 rows x 2 columns]

In [159]:
# Increase the eps value
clustering_model = DBSCAN(eps=2.0, min_samples=2, metric='precomputed')  # Adjust eps to a higher value
clusters = clustering_model.fit_predict(distance_matrix)

# Add cluster labels to the DataFrame
df['Condition_cluster'] = clusters

In [160]:
from sklearn.cluster import AgglomerativeClustering

# Apply Agglomerative Clustering
clustering_model = AgglomerativeClustering(n_clusters=30, affinity='precomputed', linkage='average')
clusters = clustering_model.fit_predict(distance_matrix)

# Add cluster labels to the DataFrame
df['Condition_cluster'] = clusters

/Users/kabirasharpe/dev/clinical-trial-trends/clinical-trial-trends/.venv/lib/python3.12/site-packages/sklearn/cluster/_agglomerative.py:1006: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(

In [161]:
# Define a mapping of keywords to groups
condition_mapping = {
    'diabetes mellitus': 'Diabetes',
    'breast neoplasms': 'Breast Cancer',  
    'chronic obstructive pulmonary disease': 'COPD',
    'rheumatoid arthritis': 'Rheumatoid Arthritis',
    'hypertension': 'Hypertension',
    'human influenza': 'Influenza',
    'asthma': 'Asthma',
    'schizophrenia': 'Schizophrenia',
    'diabetes mellitus type 2': 'Diabetes',
    'lung neoplasms': 'Lung Cancer',
    'alzheimer disease': 'Alzheimer\'s Disease',
    'hepatitis': 'Hepatitis',
    'psoriasis': 'Psoriasis',
    'hypercholesterolemia': 'Hypercholesterolemia',
    'hiv infections': 'HIV Infections',
    'prostatic neoplasms': 'Prostate Cancer',
    'infections': 'Infections',
    'colorectal neoplasms': 'Colorectal Cancer',
    'hepatitis b': 'Hepatitis B',
    'anemia': 'Anemia',
    

    # Add more keywords and groups as needed
}

# Map conditions to groups
def map_condition(condition):
    for keyword, group in condition_mapping.items():
        if keyword in condition:
            return group
    return 'Other'

df['Condition_grouped'] = df['Condition_cleaned'].apply(map_condition)

In [162]:
from sklearn.manifold import TSNE

# Reduce dimensionality with t-SNE
tsne = TSNE(n_components=2, random_state=42)
reduced_data = tsne.fit_transform(tfidf_matrix.toarray())

# Apply DBSCAN on reduced data
clustering_model = DBSCAN(eps=1.0, min_samples=2)
clusters = clustering_model.fit_predict(reduced_data)

# Add cluster labels to the DataFrame
df['Condition_cluster'] = clusters

In [163]:
num_unique = df['Condition_grouped'].nunique()
print(num_unique)

16

In [164]:
print(df['Condition_grouped'].unique())

['Other' 'Asthma' 'Hypertension' 'Psoriasis' 'Breast Cancer' 'Diabetes'
 'Hepatitis' 'Infections' 'Anemia' 'Hypercholesterolemia' 'Schizophrenia'
 'Colorectal Cancer' 'HIV Infections' 'Lung Cancer' "Alzheimer's Disease"
 'Prostate Cancer']

## **Hypothesis 1:** Using Chi-Squared Test

- The number of clinical trials for a specific condition has increased over the years.