# Hypothesis Testing & EDA

## Objectives

- Carry out hypothesis testing using statistical analysis techniques.
- Carry out Qualitative Analysis.
- Carry out Predicitve Analysis using Linear Regression.

## Inputs

- data/outputs/clinical_trials_no_missing_values.csv

## Outputs

- INSERT UPDATED DATASET

_________

The clinical trials dataset with no missing values will be loaded into this notebook.

The necessary libraries to conduct the analysis will be imported into this notebook.

In [1]:
# Import necessary libraries for data analysis and visualization (assistance from CoPilot)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns  
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.manifold import TSNE
from sklearn.cluster import DBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer
import os

## Hypothesis Testing

Import the dataset as a CSV file to perform the analysis.

In [2]:
# Load the cleaned dataset 
df = pd.read_csv('../data/outputs/clinical_trials_no_missing_values.csv')
df.head()

,Unnamed: 0,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition,Start_Month_Name,Start_Year_Period,Enrolled_Participants
0,0,GSK,"An Open-Label, Non-Randomized Pharmacokinetic ...",The main purpose of this study is to compare h...,2006,9,Phase 1,29,Completed,"Purpura, Thrombocytopenic, Idiopathic",September,2006-2010,<50
1,1,Sanofi,"A Randomized, Double-blind, Placebo-controlled...",Primary Objective: To evaluate the efficacy of...,2018,11,Phase 3,360,Recruiting,Giant Cell Arteritis,November,2016-2020,100-499
2,2,Pfizer,A Multi Center Randomized Cross Over Double Bl...,This is a pilot study to generate hypotheses a...,2007,3,Phase 2,27,Completed,Prostatic Hyperplasia,March,2006-2010,<50
3,3,Novartis,"A Double-blind, Randomized, Placebo-controlled...",This study will evaluate the effect of FTY720 ...,2008,9,Phase 2,36,Completed,Asthma,September,2006-2010,<50
4,4,Novartis,"A Two Part Study Including a Randomized, Doubl...",This study is designed to enable optimal dose ...,2013,8,Phase 1,93,Terminated,Hypertension,August,2011-2015,50-99

Remove duplicated index from loaded dataset.

In [4]:
# Check if 'Unnamed: 0' exists in the DataFrame and drop it
if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)   
df.head()

,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition,Start_Month_Name,Start_Year_Period,Enrolled_Participants
0,GSK,"An Open-Label, Non-Randomized Pharmacokinetic ...",The main purpose of this study is to compare h...,2006,9,Phase 1,29,Completed,"Purpura, Thrombocytopenic, Idiopathic",September,2006-2010,<50
1,Sanofi,"A Randomized, Double-blind, Placebo-controlled...",Primary Objective: To evaluate the efficacy of...,2018,11,Phase 3,360,Recruiting,Giant Cell Arteritis,November,2016-2020,100-499
2,Pfizer,A Multi Center Randomized Cross Over Double Bl...,This is a pilot study to generate hypotheses a...,2007,3,Phase 2,27,Completed,Prostatic Hyperplasia,March,2006-2010,<50
3,Novartis,"A Double-blind, Randomized, Placebo-controlled...",This study will evaluate the effect of FTY720 ...,2008,9,Phase 2,36,Completed,Asthma,September,2006-2010,<50
4,Novartis,"A Two Part Study Including a Randomized, Doubl...",This study is designed to enable optimal dose ...,2013,8,Phase 1,93,Terminated,Hypertension,August,2011-2015,50-99

In [5]:
# Check pandas DataFrame shape
df.shape

(9439, 12)